# Generated by Django 4.1 on 2025-11-16 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_execoes', models.CharField(max_length=88)),
            ],
        ),
        migrations.CreateModel(
            name='Regras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_uso', models.CharField(max_length=88)),
                ('tipo_escrita', models.CharField(max_length=88)),
                ('tipo_paronimos', models.CharField(max_length=88)),
                ('tipo_homonimos', models.CharField(max_length=88)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavras_categoria', to='palavras.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Palavras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavras', models.CharField(max_length=88)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavra_regras', to='palavras.regras')),
            ],
        ),
    ]
